# Generated by Django 2.2 on 2021-02-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('cavern', models.CharField(blank=True, max_length=8, null=True)),
                ('cavern_ms', models.IntegerField(blank=True, null=True)),
                ('kraken', models.CharField(blank=True, max_length=8, null=True)),
                ('kraken_ms', models.IntegerField(blank=True, null=True)),
                ('yeti', models.CharField(blank=True, max_length=8, null=True)),
                ('yeti_ms', models.IntegerField(blank=True, null=True)),
                ('dragon', models.CharField(blank=True, max_length=8, null=True)),
                ('dragon_ms', models.IntegerField(blank=True, null=True)),
                ('temple', models.CharField(blank=True, max_length=8, null=True)),
                ('temple_ms', models.IntegerField(blank=True, null=True)),
                ('shrunk', models.CharField(blank=True, max_length=8, null=True)),
                ('shrunk_ms', models.IntegerField(blank=True, null=True)),
                ('mobs', models.CharField(blank=True, max_length=8, null=True)),
                ('mobs_ms', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=8, null=True)),
                ('body_ms', models.IntegerField(blank=True, null=True)),
                ('canyon', models.CharField(blank=True, max_length=8, null=True)),
                ('canyon_ms', models.IntegerField(blank=True, null=True)),
                ('excalibur', models.CharField(blank=True, max_length=8, null=True)),
                ('excalibur_ms', models.IntegerField(blank=True, null=True)),
                ('icarus', models.CharField(blank=True, max_length=8, null=True)),
                ('icarus_ms', models.IntegerField(blank=True, null=True)),
                ('celts', models.CharField(blank=True, max_length=8, null=True)),
                ('celts_ms', models.IntegerField(blank=True, null=True)),
                ('average', models.CharField(blank=True, max_length=8, null=True)),
                ('average_ms', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
