# Generated by Django 2.2 on 2021-02-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=9)),
                ('player', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=8)),
                ('video', models.CharField(max_length=100)),
            ],
        ),
    ]
